name: Spelling

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:

env:
  CLICOLOR: 1

jobs:
  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Spell Check Repo
        uses: crate-ci/typos@v1.29.4
